name: Build

on:
  push:
    branches: [ main ]
    tags: '**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --no-restore --verbosity normal

    - name: Get version
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: echo "VERSION=$(git describe --tags --dirty)" >> $GITHUB_ENV

    - name: Pack
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: dotnet pack --configuration Release -o artifacts/ -p:Version=$VERSION

    - name: Push
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: dotnet nuget push artifacts/**.nupkg -s nuget.org --api-key ${{secrets.NUGET_API_KEY}}
